### PR TITLE
Sim players!

### PR DESCRIPTION
**Pull request by girayozil**

### CODE REVIEW

**Comment by girayozil** [comment]
Most of this is Blueprints unfortunately. I will paste them here as much as possible.

**Comment by girayozil** [comment]
image

**Comment by girayozil** [comment]
SimulatedPlayerCharacter_BP, the behavior tree and blackboard are the defaults that come with the GDK template project.

**Comment by peterimprobable** [comment]
We use BP_* instead of *_BP for all of the other assets in the project. We should keep this consistent.

**Comment by peterimprobable** [comment]
What changes have occurred in the maps, just adding NavMeshBounds?

**Comment by girayozil** [comment]
@peterimprobable Probably, I'm not sure unfortunately as changes were made by Kevin.

**Pull request merged**
