### PR TITLE
bugfix/UNR-3289/Fix spatial commands on workers on native windows

### PR DESCRIPTION
**Pull request by antoinecordelle**
When working on native windows (such as cmd), echo wasn't found in the path and the commands failed. 

This PR ensures the modified commands work on native windows while still working using unix toolings (cmdler for instance)

### CODE REVIEW

**Review by jessicafalk — APPROVED** [review]

**Comment by antoinecordelle** [comment]
This solution is a trade-off between Mac and Window:

Will work anyway: Cmdler, Git Bash and other Unix tooling based terminals
Worked and won't work anymore: MacOS
Will now work: Powershell and Windows cmd prompt
To keep in mind, those commands are highlighting a No-Op

"steps": [{"name": "No-op", "command": "echo", "arguments": ["No-op."]}]
The command field directly calls the specified key in the path, so we can't inject any conditional statement on the OS here (or anything that is not on the path, so for instance even cmd /k echo won't work as it's not in the path). The json tree used has a rigid structure and it doesn't seem to accept windows or macos conditions on the build commands.

**Comment by mironec** [comment]
I thought echo was a supported binary in windows? Does it not mesh well with how spatial calls these?

**Comment by antoinecordelle** [comment]
> @improbable-danny : I thought echo was a supported binary in windows? Does it not mesh well with how spatial calls these?

When running on master `spatial worker codegen` on Powershell and command prompt I get this : 
```
PS C:\dev\UnrealEngine\Samples\UnrealGDKExampleProject\spatial> spatial worker codegen                                                                                                                                                                                         Running task 'codegen' for 'DeploymentManager'                                                                                                                                                                                                                                 [1/1] > Codegen ** Load Unity to generate code **                                                                                                                                                                                                                              Encountered an error running command: 'echo' with arguments 'No-op.': exec: "echo": executable file not found in %PATH% 
```
This seems to depend on the Windows setup though, as Jessica doesn't have the same issue

**Comment by jessicafalk** [comment]
yeah I thought as well that echo would work. but it seems like it's not completely supported by default :(

**Review by improbable-danny — APPROVED** [review]

**Pull request merged**
