### PR TITLE
[UNR-3044][MS] Fixing crash when clicking cancel button 

### PR DESCRIPTION
**Pull request by MatthewSandfordImprobable**
The developmentplayercontroller BeginPlay calls ConnectionManager->Connect. We only need to do this if we are using a dev auth token. Additionally we need to disconnect from the deployment when we click the cancel button so that when we do that connect from developmentplayercontroller we don't actually connect and instead do some funky funky logic.

### CODE REVIEW

**Comment by MatthewSandfordImprobable** [comment]
There is a question as to in GDKWidget if we should call SpatialGameInstance::DestroyConnectionManager or SpatialConnectionManager::DstroyConnection

**Comment by MatthewSandfordImprobable** [comment]
The thing is ADeploymentsPlayerController::BeginPlay() uses the SpatialConnectionManager to register so we kinda of need to use SpatialConnectionManager::DestroyConnection.

**Comment by mironec** [comment]
Is this critical for master? Can it wait until we merge preview into master?

**Comment by MatthewSandfordImprobable** [comment]
Yeah we can hold off. I guess as it was an assert thought it would be nice to get in but yeah, not many people are going to hit this..

**Comment by MatthewSandfordImprobable** [comment]
Closing for now as we can add after release.

**Pull request closed without merging**
